### ISSUE TITLE
readlink -f fails on Mac

### ISSUE THREAD

**Issue by ColinEberhardt** [tpimh/wasm-toolchain#2]
https://github.com/tpimh/wasm-toolchain/blob/8b4ad4756f89d114334904d757789a7e96698715/c2wasm#L3

looks like a solution similar to this one is needed: https://github.com/yarnpkg/yarn/issues/2511

(by the way, thanks for this really useful repo 👍 )

**Comment by tpimh** [comment]
What about just replacing `readlink -f` with `realpath`? Does it work on Mac?

**Comment by ColinEberhardt** [comment]
Yes, that works just fine on Mac. I'm not able to test whether that works on Linux though.

**Comment by tpimh** [comment]
I tested it on a couple of systems, should be fine.
